server:
  port: 80


eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

spring:
  application:
    #eureka一定要配置应用名称
    name: consumer-order
